#[[ -f ~/.config/bash/bashrc ]] && . ~/.config/bash/bashrc

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share

# ZSH directory
export ZDOTDIR=$HOME/.config/zsh
